import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import Featured from "../components/Featured.js";
import ProductList from "../components/ProductList";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurant </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <ProductList />
    </div>
  );
}
